[build-system]
requires = [
    "wheel",
    "setuptools>=45",
    "setuptools_scm[toml]>=6.0",
    "cmake_build_extension",
    "PySide2",
    "shiboken2",
    "shiboken2_generator"
]
build-backend = "setuptools.build_meta"
